version: '3'

services:
  ci:
    image: jenkinsci/blueocean
    ports:
      - '8080:8080'
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
  docker-agent:
    image: docker:dind
    privileged: true

volumes:
  jenkins-data: